name: test3
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - argh=0.26.2
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - cairo=1.14.12
  - certifi=2020.11.8
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.4.1
  - configparser=5.0.1
  - convertdate=2.2.1
  - cryptography=2.9.2
  - cycler=0.10.0
  - cython=0.29.17
  - cytoolz=0.10.1
  - dask-core=2.16.0
  - dbus=1.13.14
  - decorator=4.4.2
  - defusedxml=0.6.0
  - docker-pycreds=0.4.0
  - expat=2.2.6
  - fbprophet=0.5
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gitdb=4.0.5
  - glib=2.63.1
  - gmp=6.1.2
  - gql=0.1.0
  - graphite2=1.3.13
  - graphql-core=3.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - holidays=0.9.11
  - icu=58.2
  - idna=2.9
  - imageio=2.8.0
  - importlib_metadata=1.5.0
  - intel-openmp=2020.1
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jasper=2.0.14
  - jedi=0.17.0
  - jinja2=2.11.2
  - joblib=0.14.1
  - jpeg=9b
  - json5=0.9.0
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - jupyterlab=2.1.2
  - jupyterlab_server=1.1.3
  - kiwisolver=1.2.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libsodium=1.0.16
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.9
  - lunardate=0.2.0
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.2
  - networkx=2.4
  - ninja=1.9.0
  - nodejs=10.13.0
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - nvidia-ml=7.352.0
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1h
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pathtools=0.1.2
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.1.2
  - pip=20.0.2
  - pixman=0.38.0
  - prometheus_client=0.7.1
  - promise=2.3
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - ptyprocess=0.6.0
  - py-opencv=3.4.2
  - pycparser=2.20
  - pygments=2.6.1
  - pymeeus=0.3.7
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - pystan=2.17.1.0
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.5.0
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.7.3
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.23.0
  - scikit-image=0.16.2
  - scikit-learn=0.23.2
  - scipy=1.4.1
  - send2trash=1.5.0
  - sentry-sdk=0.19.4
  - setuptools=46.2.0
  - shortuuid=1.0.1
  - sip=4.19.8
  - six=1.14.0
  - smmap=3.0.4
  - sqlite=3.31.1
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.8
  - toolz=0.10.0
  - torchaudio=0.5.0
  - torchtext=0.6.0
  - torchvision=0.6.0
  - tornado=6.0.4
  - tqdm=4.46.0
  - traitlets=4.3.3
  - urllib3=1.25.9
  - wandb=0.10.11
  - watchdog=0.10.4
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wget=1.20.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.1
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.9.0
    - adal==1.2.3
    - alabaster==0.7.12
    - argparse==1.4.0
    - azure-applicationinsights==0.1.0
    - azure-batch==9.0.0
    - azure-common==1.1.25
    - azure-core==1.5.0
    - azure-cosmosdb-nspkg==2.0.2
    - azure-cosmosdb-table==1.0.6
    - azure-datalake-store==0.0.48
    - azure-eventgrid==1.3.0
    - azure-graphrbac==0.61.1
    - azure-keyvault==4.1.0
    - azure-keyvault-certificates==4.1.0
    - azure-keyvault-keys==4.1.0
    - azure-keyvault-secrets==4.1.0
    - azure-loganalytics==0.1.0
    - azure-mgmt-advisor==4.0.0
    - azure-mgmt-applicationinsights==0.3.0
    - azure-mgmt-authorization==0.60.0
    - azure-mgmt-batch==8.0.0
    - azure-mgmt-billing==0.2.0
    - azure-mgmt-cdn==4.0.0
    - azure-mgmt-cognitiveservices==6.1.0
    - azure-mgmt-commerce==1.0.1
    - azure-mgmt-compute==12.0.0
    - azure-mgmt-consumption==3.0.0
    - azure-mgmt-containerinstance==1.5.0
    - azure-mgmt-containerregistry==2.8.0
    - azure-mgmt-containerservice==9.0.1
    - azure-mgmt-cosmosdb==0.14.0
    - azure-mgmt-datafactory==0.10.0
    - azure-mgmt-datalake-analytics==0.6.0
    - azure-mgmt-datalake-nspkg==3.0.1
    - azure-mgmt-datalake-store==0.5.0
    - azure-mgmt-datamigration==4.0.0
    - azure-mgmt-devspaces==0.2.0
    - azure-mgmt-devtestlabs==4.0.0
    - azure-mgmt-dns==3.0.0
    - azure-mgmt-eventgrid==2.2.0
    - azure-mgmt-eventhub==3.0.0
    - azure-mgmt-hanaonazure==0.13.0
    - azure-mgmt-iotcentral==3.0.0
    - azure-mgmt-iothub==0.12.0
    - azure-mgmt-iothubprovisioningservices==0.2.0
    - azure-mgmt-keyvault==2.2.0
    - azure-mgmt-loganalytics==0.5.0
    - azure-mgmt-logic==3.0.0
    - azure-mgmt-machinelearningcompute==0.4.1
    - azure-mgmt-managementgroups==0.2.0
    - azure-mgmt-managementpartner==0.1.1
    - azure-mgmt-maps==0.1.0
    - azure-mgmt-marketplaceordering==0.2.1
    - azure-mgmt-media==2.1.0
    - azure-mgmt-monitor==0.9.0
    - azure-mgmt-msi==1.0.0
    - azure-mgmt-network==10.1.0
    - azure-mgmt-notificationhubs==2.1.0
    - azure-mgmt-nspkg==3.0.2
    - azure-mgmt-policyinsights==0.5.0
    - azure-mgmt-powerbiembedded==2.0.0
    - azure-mgmt-rdbms==2.2.0
    - azure-mgmt-recoveryservices==0.5.0
    - azure-mgmt-recoveryservicesbackup==0.7.0
    - azure-mgmt-redis==6.0.0
    - azure-mgmt-relay==0.2.0
    - azure-mgmt-reservations==0.7.0
    - azure-mgmt-resource==9.0.0
    - azure-mgmt-scheduler==2.0.0
    - azure-mgmt-search==2.1.0
    - azure-mgmt-servicebus==0.6.0
    - azure-mgmt-servicefabric==0.4.0
    - azure-mgmt-signalr==0.3.0
    - azure-mgmt-sql==0.18.0
    - azure-mgmt-storage==10.0.0
    - azure-mgmt-subscription==0.5.0
    - azure-mgmt-trafficmanager==0.51.0
    - azure-mgmt-web==0.46.0
    - azure-nspkg==3.0.2
    - azure-servicebus==0.50.2
    - azure-servicefabric==7.0.0.0
    - azure-servicemanagement-legacy==0.20.7
    - azure-storage-blob==12.3.1
    - azure-storage-common==2.1.0
    - azure-storage-file==2.1.0
    - azure-storage-queue==12.1.1
    - babel==2.8.0
    - boilr==0.5.1
    - boto==2.49.0
    - boto3==1.13.8
    - botocore==1.16.8
    - brewer2mpl==1.4.1
    - cachetools==4.1.0
    - colorama==0.4.3
    - distro==1.5.0
    - docopt==0.6.2
    - docutils==0.15.2
    - dotnetcore2==2.1.14
    - entrypoints==0.3
    - fastparquet==0.4.0
    - fire==0.3.1
    - future==0.18.2
    - gensim==3.8.3
    - gitpython==3.1.9
    - google-auth==1.14.3
    - google-auth-oauthlib==0.4.1
    - grpcio==1.28.1
    - h5py==2.10.0
    - horovod==0.19.1
    - imagesize==1.2.0
    - imutils==0.5.3
    - isodate==0.6.0
    - jmespath==0.9.5
    - jsonpatch==1.26
    - jsonpickle==1.4.1
    - jsonpointer==2.0
    - keras==2.3.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.1
    - keras2onnx==1.6.1
    - llvmlite==0.32.1
    - markdown==3.2.2
    - msrest==0.6.13
    - msrestazure==0.6.3
    - munch==2.5.0
    - nltk==3.5
    - numba==0.49.1
    - oauthlib==3.1.0
    - onnx==1.7.0
    - onnxconverter-common==1.6.1
    - onnxmltools==1.6.1
    - onnxruntime==1.2.0
    - opencv-python==4.5.2.52
    - packaging==20.3
    - progressbar33==2.4
    - protobuf==3.11.3
    - psutil==5.7.0
    - py-cpuinfo==7.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyjwt==1.7.1
    - python-graphviz==0.14
    - pyyaml==5.3.1
    - regex==2020.5.7
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - s3transfer==0.3.3
    - sacred==0.8.1
    - seaborn==0.11.0
    - skl2onnx==1.6.1
    - smart-open==2.0.0
    - snowballstemmer==2.0.0
    - sphinx==3.0.3
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - subprocess32==3.5.4
    - tensorboard==2.2.1
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorboardx==2.1
    - termcolor==1.1.0
    - thrift==0.13.0
    - torchfile==0.1.0
    - torchsummary==1.5.1
    - typing-extensions==3.7.4.2
    - uamqp==1.2.7
    - visdom==0.1.8.9
    - websocket-client==0.57.0
    - werkzeug==1.0.1
    - wrapt==1.12.1
